version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: aws-sdk
    versions:
    - 2.865.0
    - 2.890.0
    - 2.894.0
